# These track the column number of each player attribute in playerlist.csv file
# Note that change in csv column order can be edited here.
player_attribute_index:
  name: 0
  telegram_username: 1
  house_number: 2
  room_number: 3
  faculty: 4
  gender_pref: 5
  gender: 6
  year_of_study: 7
  comments: 8
  likes: 9
  dislikes: 10

